"""Design Plan Page: browse the generated hardware plan and unified design context."""

from __future__ import annotations

import streamlit as st


def render() -> None:
    st.title("📋 Hardware Design Plan & Specification")
    st.caption("Inspect the structured submodule plan, bus mappings, and the intermediate Unified Design Context.")

    if "design_results" not in st.session_state:
        st.info("💡 No active design results found in this session. Head to the **Hardware Design** page to start a new generation.")
        return

    results = st.session_state["design_results"]
    plan = results["plan"]
    design_spec = results["design_spec"]

    tab_spec, tab_plan = st.tabs(["📄 Unified Design Specification", "🏗️ Hardware Architecture Plan"])

    with tab_spec:
        st.markdown("### Unified Design Context Specification")
        st.caption("Consolidated single-source-of-truth document containing requirements, architecture plan, and protocol constraints.")
        st.markdown(design_spec)

    with tab_plan:
        st.markdown("### Hardware Architecture Plan")
        st.caption("Structured planning schema generated by the planning agent.")
        
        st.markdown(f"**System Architecture Overview:** {plan.get('system_architecture', '')}")
        st.markdown(f"**Registers Summary:** {plan.get('registers_summary', 'N/A')}")
        st.markdown(f"**Memories Summary:** {plan.get('memories_summary', 'N/A')}")
        
        st.divider()
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("Submodules Hierarchy")
            for sub in plan.get("submodules", []):
                with st.container(border=True):
                    st.markdown(f"**Module:** `{sub['name']}`")
                    st.write(f"Purpose: {sub['purpose']}")
                    st.write(f"Ports: {', '.join(sub['interfaces'])}")
                    
        with col2:
            st.subheader("Clock & Reset Domains")
            for clk in plan.get("clock_domains", []):
                with st.container(border=True):
                    st.markdown(f"**Clock:** `{clk['name']}`")
                    st.write(f"Reset: {clk['reset_strategy']}")
                    st.write(f"Description: {clk['description']}")

        st.divider()
        st.subheader("FSM Architecture")
        fsm = plan.get("fsm_architecture", {})
        st.write(fsm.get("description", ""))
        
        fsm_cols = st.columns(len(fsm.get("states", [])) or 1)
        for idx, state in enumerate(fsm.get("states", [])):
            with fsm_cols[idx % len(fsm_cols)]:
                with st.container(border=True):
                    st.markdown(f"**State:** `{state['name']}`")
                    st.caption(state.get("actions", ""))
